<?xml version="1.0" encoding="utf-8"?><Database Name="VirtualLib" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=virlib.database.windows.net;Initial Catalog=VirtualLib;User ID=ILBooks" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VirtualLibConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Press" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Pages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_UserBook" Member="UserBooks" ThisKey="Id" OtherKey="BookID" Type="UserBook" />
      <Association Name="Book_BooksRead" Member="BooksReads" ThisKey="Id" OtherKey="BookID" Type="BooksRead" />
    </Type>
  </Table>
  <Table Name="dbo.UserBook" Member="UserBooks">
    <Type Name="UserBook">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_UserBook" Member="Book" ThisKey="BookID" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="User_UserBook" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BooksRead" Member="BooksReads">
    <Type Name="BooksRead">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_BooksRead" Member="Book" ThisKey="BookID" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="User_BooksRead" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permission" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserBook" Member="UserBooks" ThisKey="Id" OtherKey="UserID" Type="UserBook" />
      <Association Name="User_BooksRead" Member="BooksReads" ThisKey="Id" OtherKey="UserID" Type="BooksRead" />
    </Type>
  </Table>
</Database>